# user's config file for testing proc

## data analysis:
eval_unit_size: 1
eval_unit_met: mean
shuffled: False
random_seed: 1
normal_test_alpha: 0.05


## sig testing
sig_test_alpha: 0.05
sig_boot_perm_B: 500

## effect size
eff_size_ind: cohend

## power analysis
power_alpha: 0.05
power_method: bootstrap
power_dist_name: normal
power_num_of_subsample: 35 # number of simulations 
power_B: 200



## output
fig_output_dir: figures
#report_output_dir: report